import time 
a=int(input("enter the value of a:"))
b=float(input("enter the value of b:"))
c=str(input("enter the value of c:"))
d=bool(input("enter the value of d:"))
e=complex(input("enter the value of e:"))
print()
print("value of a is:",a)
print("value of b is:",b)
print("value of c is:",c)
print("value of d is:",d)
print("value of e is:",e)
print()
print("type of value of a is:",type(a))
print("type of value of b is:",type(b))
print("type of value of c is:",type(c))
print("type of value of d is:",type(d))
print("type of value of e is:",type(e))
print()
print("address of value of a is:",id(a))
print("address of value of b is:",id(b))
print("address of value of c is:",id(c))
print("address of value of d is:",id(d))
print("address of value of e is:",id(e))
print()
print(a==b)
print(b==c)
print(c==d)
print(d==e)
print(e==a)
print()
print(a!=b)
print(b!=c)
print(c!=d)
print(d!=e)
print(e!=a)
print()
time.sleep(5)
print('end of an application')

